from __future__ import annotations

DOC_STATUS_UPLOADED = "uploaded"
DOC_STATUS_PARSING = "parsing"
DOC_STATUS_PARSED = "parsed"
DOC_STATUS_EMBEDDING = "embedding"
DOC_STATUS_INDEXED = "indexed"
DOC_STATUS_FAILED = "failed"

ALLOWED_TRANSITIONS = {
    DOC_STATUS_UPLOADED: {DOC_STATUS_PARSING, DOC_STATUS_FAILED},
    DOC_STATUS_PARSING: {DOC_STATUS_PARSED, DOC_STATUS_FAILED},
    DOC_STATUS_PARSED: {DOC_STATUS_EMBEDDING, DOC_STATUS_FAILED},
    DOC_STATUS_EMBEDDING: {DOC_STATUS_INDEXED, DOC_STATUS_FAILED},
    DOC_STATUS_INDEXED: {DOC_STATUS_PARSING, DOC_STATUS_FAILED},
    DOC_STATUS_FAILED: {DOC_STATUS_PARSING},
}
